version: '3.8'

services:

  # Host======================================================================
  nginx:
    image: nginx:1.25.1
    container_name: nginx
    working_dir: /var/www/html/
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/

  # App=======================================================================
  app:
    container_name: app
    build: docker/app
    volumes:
      - ./app/:/var/www/html/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini

  # NPM=======================================================================
  node:
    image: node:18.16.1
    container_name: node
    volumes:
      - ./app/:/var/www/html/
#      - node:/var/www/html/node_modules ここもwindows特有のエラー対策
    working_dir: /var/www/html/
    entrypoint: [ "npm" ]
#    command: [ "run", "dev" ] // コンテナログイン & バージョン確認用

  # Database==================================================================
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: 'laravel-database'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - laravel-db:/var/lib/mysql
    ports:
      - "3306:3306"

#  puppeteer-node:
#    build:
#      context: ./
#      dockerfile: ./docker/puppeteer-node/Dockerfile
#    container_name: puppeteer-node
#    volumes:
#      - ./preview:/var/www/html/
#    working_dir: /var/www/html/
#    tty: true

volumes:
  laravel-db:
    driver: local

# windows環境で発生するnpm周りのエラー対策
#
#  node:
#    driver: local
